// Mocks generated by Mockito from annotations
// in catbreeds/test/cats/data/repositories/cats_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:catbreeds/cats/data/datasources/dtos/cat_dto.dart' as _i4;
import 'package:catbreeds/cats/data/datasources/local/cats_datasource_local.dart'
    as _i3;
import 'package:catbreeds/cats/data/datasources/remote/cats_datasource_remote.dart'
    as _i5;
import 'package:core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CatsDatasourceLocal].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatsDatasourceLocal extends _i1.Mock
    implements _i3.CatsDatasourceLocal {
  MockCatsDatasourceLocal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.CatDto> fetchCats() => (super.noSuchMethod(
    Invocation.method(#fetchCats, []),
    returnValue: <_i4.CatDto>[],
  ) as List<_i4.CatDto>);

  @override
  void saveCats(List<_i4.CatDto>? cats) => super.noSuchMethod(
    Invocation.method(#saveCats, [cats]),
    returnValueForMissingStub: null,
  );

  @override
  void saveCat(_i4.CatDto? cat) => super.noSuchMethod(
    Invocation.method(#saveCat, [cat]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.CatDto? getCatById(String? catId) =>
      (super.noSuchMethod(Invocation.method(#getCatById, [catId]))
          as _i4.CatDto?);
}

/// A class which mocks [CatsDatasourceRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatsDatasourceRemote extends _i1.Mock
    implements _i5.CatsDatasourceRemote {
  MockCatsDatasourceRemote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ApiResponse<List<_i4.CatDto>>> fetchCats() =>
      (super.noSuchMethod(
        Invocation.method(#fetchCats, []),
        returnValue: _i6.Future<_i2.ApiResponse<List<_i4.CatDto>>>.value(
          _FakeApiResponse_0<List<_i4.CatDto>>(
            this,
            Invocation.method(#fetchCats, []),
          ),
        ),
      ) as _i6.Future<_i2.ApiResponse<List<_i4.CatDto>>>);
}
