// Mocks generated by Mockito from annotations
// in catbreeds/test/cats/data/datasources/remote/cats_datasource_remote_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:catbreeds/cats/data/datasources/dtos/cat_dto.dart' as _i5;
import 'package:catbreeds/cats/data/services/cats_api_services.dart' as _i3;
import 'package:core/core.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CatsApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatsApiServices extends _i1.Mock implements _i3.CatsApiServices {
  MockCatsApiServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<List<_i5.CatDto>>> getCats() =>
      (super.noSuchMethod(
        Invocation.method(#getCats, []),
        returnValue: _i4.Future<_i2.HttpResponse<List<_i5.CatDto>>>.value(
          _FakeHttpResponse_0<List<_i5.CatDto>>(
            this,
            Invocation.method(#getCats, []),
          ),
        ),
      ) as _i4.Future<_i2.HttpResponse<List<_i5.CatDto>>>);
}
