// Mocks generated by Mockito from annotations
// in catbreeds/test/cats/data/datasources/local/cats_datasource_local_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:core/src/data/cache/cache_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CacheClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheClient extends _i1.Mock implements _i2.CacheClient {
  MockCacheClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T? read<T>({required String? key}) =>
      (super.noSuchMethod(Invocation.method(#read, [], {#key: key})) as T?);

  @override
  List<T> readAll<T>() =>
      (super.noSuchMethod(Invocation.method(#readAll, []), returnValue: <T>[])
          as List<T>);

  @override
  void write<T>({required String? key, required T? value}) =>
      super.noSuchMethod(
        Invocation.method(#write, [], {#key: key, #value: value}),
        returnValueForMissingStub: null,
      );

  @override
  void delete({required String? key}) => super.noSuchMethod(
    Invocation.method(#delete, [], {#key: key}),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  bool containsKey({required String? key}) => (super.noSuchMethod(
    Invocation.method(#containsKey, [], {#key: key}),
    returnValue: false,
  ) as bool);
}
