name: core
description: "Core package"
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.2.0
  networking:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

